### ISSUE TITLE
parafib error: MPSC channel size was 512 

### ISSUE THREAD

**Issue by lessneek** [mratsim/weave#105]
```
$ nim -v                          
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-08
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

parafib.nim:
```nim
import weave

proc fib(n: int): int =
  # int64 on x86-64
  if n < 2:
    return n

  let x = spawn fib(n-1)
  let y = fib(n-2)

  result = sync(x) + y

proc main() =
  var n = 20

  init(Weave)
  let f = fib(n)
  exit(Weave)

  echo f

main()
```

```
nim c --threads:on ./parafib.nim
```

```
Error: unhandled exception: ~/.nimble/pkgs/weave-0.1.0/weave/memory/memory_pools.nim(625, 8) `sizeof(ChannelMpscUnboundedBatch[ptr MemBlock]) == 272` MPSC channel size was 512 [AssertionError]
```

**Comment by mratsim** [comment]
Works for me on one of the commits from yesterday, will try updating to see if there is a regression.
Was your compiler installed through choosenim?

![image](https://user-images.githubusercontent.com/22738317/74133903-df0f3380-4be9-11ea-8090-c234b82c9635.png)

**Comment by mratsim** [comment]
Recompiled on the latest commit, it still works

![image](https://user-images.githubusercontent.com/22738317/74134779-6ad58f80-4beb-11ea-8f76-275ed327cc95.png)

My guess is that somehow the compiler you compiled on 2020-02-08 was from before:
- PR: https://github.com/nim-lang/Nim/issues/13122
- commit: https://github.com/nim-lang/Nim/commit/abea80376a113fb218c22b6474727c279e694cd3

**Comment by mratsim** [comment]
Sorry, actually the issue is the following:

- you are using Weave 0.1.0, it is not compatible with the devel from after commit https://github.com/nim-lang/Nim/commit/abea80376a113fb218c22b6474727c279e694cd3
- You need to install Weave devel as well: `nimble install weave@#master` for compatibility with the latest Nim devel.
