### ISSUE TITLE
getThreadId not in the range 0 ..< number of threads

### ISSUE THREAD

**Issue by olliNiinivaara** [mratsim/weave#126]
getThreadId returns the linux process id (typically numbers like 28423, 28424, ...)

It would be appreciated if it really returned an id incrementing from zero, because now I have to use lock and iteration to map the PID to array index:

https://github.com/olliNiinivaara/GuildenStern/blob/4b52391f7b7b7eb676db60a11534327ae197566e/src/guildenstern/dispatcher.nim#L84-L97

**Comment by mratsim** [comment]
That's very strange, it returns the ID I use internally and those are in the 0 ..< WEAVE_NUM_THREADS range:

https://github.com/mratsim/weave/blob/996c53caaffc6617d5f16572bfd8357f20047d4f/weave/runtime.nim#L124-L128

**Comment by olliNiinivaara** [comment]
this one is easy to reproduce:
test.nim:
```
import weave
echo weave.getThreadId()
```
```
olli@nexus:~/Nim/Testit$ nim c -r --threads:on --hints:off test.nim
31128
```

**Comment by mratsim** [comment]
Mmmh it seems like you are calling the `getThreadId` from Nim threads https://nim-lang.org/docs/threads.html#getThreadId

You need to use `Weave` with a capital letter to use my overloaded ID (and make sure to init the runtime)
```Nim
import weave
init(Weave)
echo Weave.getThreadId()
exit(Weave)
```

**Comment by olliNiinivaara** [comment]
Yes! It was wrong case in one letter. Weave works.
(and also having 2 procs with name getThreadId ... Murphy's law)
thanks, case closed.
