### ISSUE TITLE
"nimble install weave" fails on Ubuntu 18

### ISSUE THREAD

**Issue by greenersharp** [mratsim/weave#199]
nimble install weave

Downloading https://github.com/mratsim/weave using git
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: git clone --recursive --depth 1 -b v0.4.0 https://github.com/mratsim/weave /tmp/nimble_14118/githubcom_mratsimweave
        ... Output: Cloning into '/tmp/nimble_14118/githubcom_mratsimweave'...
        ... Note: checking out 'ce8cac849b1c21b92a8b41cf52dc51c8b959a053'.
        ... You are in 'detached HEAD' state. You can look around, make experimental
        ... changes and commit them, and you can discard any commits you make in this
        ... state without impacting any branches by performing another checkout.
        ... If you want to create a new branch to retain commits you create, you may
        ... do so (now or later) by using -b with the checkout command again. Example:
        ...   git checkout -b <new-branch-name>
        ... Submodule 'benchmarks/vendor/bots' (https://github.com/bsc-pm/bots) registered for path 'benchmarks/vendor/bots'
        ... Submodule 'benchmarks/vendor/fibril' (https://github.com/chaoran/fibril) registered for path 'benchmarks/vendor/fibril'
        ... Submodule 'benchmarks/vendor/mkl-dnn' (https://github.com/intel/mkl-dnn) registered for path 'benchmarks/vendor/mkl-dnn'
        ... Submodule 'benchmarks/vendor/staccato' (https://github.com/rkuchumov/staccato) registered for path 'benchmarks/vendor/staccato'
        ... Submodule 'benchmarks/vendor/tasking-2.0' (https://github.com/aprell/tasking-2.0) registered for path 'benchmarks/vendor/tasking-2.0'
        ... Submodule 'benchmarks/vendor/uts-benchmark-code' (https://git.code.sf.net/p/uts-benchmark/code) registered for path 'benchmarks/vendor/uts-benchmark-code'
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/bots'...
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/fibril'...
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/mkl-dnn'...
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/staccato'...
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/tasking-2.0'...
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/uts-benchmark-code'...
        ... fatal: unable to access 'https://git.code.sf.net/p/uts-benchmark/code/': server certificate verification failed. CAfile: none CRLfile: none
        ... fatal: clone of 'https://git.code.sf.net/p/uts-benchmark/code' into submodule path '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/uts-benchmark-code' failed
        ... Failed to clone 'benchmarks/vendor/uts-benchmark-code'. Retry scheduled
        ... Cloning into '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/uts-benchmark-code'...
        ... fatal: unable to access 'https://git.code.sf.net/p/uts-benchmark/code/': server certificate verification failed. CAfile: none CRLfile: none
        ... fatal: clone of 'https://git.code.sf.net/p/uts-benchmark/code' into submodule path '/tmp/nimble_14118/githubcom_mratsimweave/benchmarks/vendor/uts-benchmark-code' failed
        ... Failed to clone 'benchmarks/vendor/uts-benchmark-code' a second time, aborting

**Comment by mratsim** [comment]
I'll tag a new version, in the meantime use `nimble install weave@#head` to install the newest version.

**Comment by greenersharp** [comment]
It fails with the same error.   It seems to be a problem with the https://code.sf.net/ domain

**Comment by greenersharp** [comment]
seems to work now !
