### ISSUE TITLE
The MPSC channel has a deadlock

### ISSUE THREAD

**Issue by mratsim** [mratsim/weave#6]
The MPSC channel for StealRequest has a deadlock

Reproducible with 5 workers on Fibonacci.

Also it might be worth it to move to a lock-free design even though the lock-based design is not a bottleneck.

**Comment by mratsim** [comment]
Not sure what caused the deadlock as it's just a streamlined implementation of the legacy channels, could it have been false sharing?
Anyway, unused after #21 and e41c927865e0a7d09f8de9fd8a67e614e9748619

**Comment by aprell** [comment]
Is this deadlock reproducible with the C version?

**Comment by mratsim** [comment]
No it's only my own channel reimplementation.

When I switched to the 1-to-1 reimplementation of your Nim channels (https://github.com/mratsim/weave/commit/04c355dcb7275f3236b888dc2938edda0bd58ccb) it disappeared.

**Comment by mratsim** [comment]
So I manage to get it again while changing the implementation of the MPSC queue to yet another one lock-free queue (suitable for batching for my memory manager)

The main difference is that it uses compare-and-swap which are more heavy on cache lines so maybe behave worse under contention. Steal backoff might help here

It's probably a livelock and not a deadlock, it may be unrelated but it's very annoying nonetheless.

It happens reliably even on just a hello world
https://github.com/mratsim/weave/blob/e3a1f2944a1bf3bdd25155a4c220b7aabdf38a93/weave/async.nim#L138-L151

The main thread always get stucks in this loop in the runtime barrier
https://github.com/mratsim/weave/blob/9f4abc48dbe043dc1d51656bf4ee59eb8588b654/weave/runtime.nim#L124-L138

adding some printing in declining or the steal request relay (or uncommenting the debugTermination log) will unstuck the runtime for a 20% perf loss :P.

https://github.com/mratsim/weave/blob/9f4abc48dbe043dc1d51656bf4ee59eb8588b654/weave/scheduler.nim#L79-L89

https://github.com/mratsim/weave/blob/9f4abc48dbe043dc1d51656bf4ee59eb8588b654/weave/thieves.nim#L96-L108

**Comment by mratsim** [comment]
False alarm, it's my queue that has an issue, I can reproduce the bug in an isolated bench.

I think I have an ABA problem with the producers' side using exchange and the consumer side using compare-exchange.
